config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: 'tasks'
  get 'tasks/new', to: 'tasks#new', as: 'new_task'
  get 'task/:id', to: 'tasks#show', as: 'task'
  post 'tasks', to: 'tasks#create'
  get 'task/:id/edit', to: 'tasks#edit', as:'edit'
  patch 'task/:id', to: 'tasks#update'
  delete 'task/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def show
    @task = Task.find(params[:id].to_i)
  end

  def edit
    @task = Task.find(params[:id].to_i)
  end

  def update
    @task = Task.find(params[:id].to_i)
    @task.update(task_params)
    redirect_to task_path(@task.id)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def find_task
    @task = Task.find(params[:id].to_i)
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

    <%= f.check_box :completed %>

  <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<div class=out>
  <h1>Edit this task</h1>
  <div class=in>
    <%= render 'form', task: @task %>
      </div>
  <div class="in">
    <p> <%= link_to "Go back to your list", tasks_path %> </p>
  </div>
</div>

app/views/tasks/index.html.erb
<div class=out>
  <h1>Do all things with love</h1>
  <div class=in>
    <ul>
    <% @tasks.each do |task| %>
    <li> <% if task.completed %>
      <i class="fas fa-heart"></i>
      <% else %>
      <i class="far fa-heart"></i>
      <% end %>
      <%= link_to task.title, task_path(task.id) %> </li>
      <% end %>
    </ul>
  </div>
  <div class="in">
    <p> <%= link_to "Add a new task here", new_task_path %> </p>
  </div>
</div>

app/views/tasks/new.html.erb
<div class=out>
  <h1>Add new things to do</h1>
  <div class=in>
    <%= render 'form', task: @task %>
  </div>
  <div class="in">
    <p> <%= link_to "Go back to your list", tasks_path %> </p>
  </div>
</div>

app/views/tasks/show.html.erb
<div class=out>

  <h1><%= @task.title  %></h1>

  <div class=in>
    <p><%= @task.details %></p>
  </div>

  <% if @task.completed %>
    <i class="fas fa-heart"></i> Task is completed! <i class="fas fa-heart"></i>
    <% else %>
    <i class="far fa-heart"></i> Still to be done, darling! <i class="far fa-heart"></i>
  <% end %>

  <div class="in">
    <i class="fas fa-pencil-alt"></i><%= link_to "Edit this task", edit_path %>
  </div>

   <div class="in">
    <p> <%= link_to "Go back to your list", tasks_path %> </p>
  </div>

</div>